### ISSUE TITLE
SmartRoot plugin in ImageJ couldn't load the "SmartRoot Explorer" page

### ISSUE THREAD

**Issue by LillyCollins** [SmartRoot/SmartRoot#30]
Hi I have been using SmartRoot to measure roots and it worked well. However, since yesterday after I clicked Plugins, SmartRoot, SR Explorer, all four new pages pop out as usual, but the SR Explorer was a blank page and cannot be opened (which should be showing the directories of the laptop and allow me to choose a picture. Below is a photo.

**Comment by LillyCollins** [comment]
[https://files.slack.com/files-pri/TAS0QF0GK-F016WETCY5V/image_from_ios.jpg](url)

**Comment by LillyCollins** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/66123699/87848019-9b002780-c91b-11ea-9279-78a54a56b592.jpg)

**Comment by LillyCollins** [comment]
It is solved. My bad - it did actually work.

**Comment by nmerryh** [comment]
Hi, Lilly. I'm experincing the same problem but haven't figured how to fix it yet. Could you please share your experience? Thanks in advance.
