### ISSUE TITLE
Use of Smart Root in Image J

### ISSUE THREAD

**Issue by iatoloye** [SmartRoot/SmartRoot#4]
I am having trouble installing image J. After the download I end up with a zip file. I copied the Smart Root folder into Image J, but the SR explorer will not lunch. Please, I need a step by step guide. 

Thank you

**Comment by guillaumelobet** [comment]
Here it is: 

- Install ImageJ (https://imagej.net/Welcome)

- Download the installation files: https://github.com/SmartRoot/SmartRoot-Installation/blob/master/SmartRoot.zip

- unzip the folder. It contains the following:
    - SmartRoot [folder]
        - Image_Explorer.jar
        - jcommon-1.0.16.jar
        - jfreechart-1.0.13.jar
        - mysql-connector-java-5.1.7-bin.jar
        - Smart_Root.jar
    - Quick Start Images [folder]
    - Quick Start SmartRoot.pdf [file]
    - SmartRoot User Guide.pdf [file]

- copy the SmartRoot folder (the one within the zipfile, that contains the jar files) to ImageJ/plugins

- start ImageJ

- Go to the `plugins >SR_Explorer` menu to launch SmartRoot
