### ISSUE TITLE
Installing on macOS High Sierra

### ISSUE THREAD

**Issue by Iwargo** [SmartRoot/SmartRoot#6]
Hi there,

I've used SmartRoot on a windows computer before and it is very helpful and informative. However now I'm having difficulty installing SmartRoot onto my Mac. I've downloaded ImageJ and it works. I downloaded the SmartRoot folder and copied it to the plugins folder under ImageJ, but it does not work. I believe this issue arises because of the High Sierra operating system, but I am unsure how to solve it. Any help would be appreciated

Thanks!

**Comment by guillaumelobet** [comment]
Hi, 
It should work without a problem. I am running SmartRoot on High Sierra as well. Just to be sure, the SmartRoot Folder you copied into `Applications > ImageJ > plugins` is the one containing only the jar files, right?

**Comment by Iwargo** [comment]
Okay so I did that and now I can open SmartRoot but I can not open any files through it. My log gives these messages
The specified database was not found.
You will not be able to write to a database.
You will still be able to export to a .csv file.

Unsure of what to do next. Thanks so much for your help

**Comment by guillaumelobet** [comment]
OK, the error message is not a problem. You will still be able to export data as a csv file. 

So, again to be sure, you are openning the file throught the SmartRoot Explorer window? Openning images through regular ImageJ will not work. 

<img width="1233" alt="screen shot 2018-02-20 at 14 55 19" src="https://user-images.githubusercontent.com/2121453/36427725-3ef93706-164e-11e8-9ab6-41c3fa9b92c4.png">

**Comment by Iwargo** [comment]
This is all I see when opening SR Explorer
<img width="1256" alt="screen shot 2018-02-20 at 9 05 07 am" src="https://user-images.githubusercontent.com/36641285/36428912-297a8a9e-161f-11e8-9430-2db3f9d2799e.png">

**Comment by guillaumelobet** [comment]
Alright, then just open the `/` folder, then `Users` and so on. You'll find all your files. Like in the picture in my previous post

**Comment by Iwargo** [comment]
There is nothing in the / folder when I click on it. do I need to add the photos to a specific folder or can they just be on my desktop
<img width="794" alt="screen shot 2018-03-18 at 12 28 49 pm" src="https://user-images.githubusercontent.com/36641285/37568192-254accb6-2aa8-11e8-8794-ea38dc1718c7.png">

**Comment by guillaumelobet** [comment]
Sorry for this simple question, but did you try double clicking on it?

**Comment by nmerryh** [comment]
Hi, sorry for asking this after a few years but I'm experiencing the same problem now. I've installed smartRoot on my M1 MacBook and managed to open all the SmartRoot windows. However, my SmarRoot explorer window doesn't show anything. Exactly like Iwargo's case. Already tried to double-click on it, but still now showing anything. Kindly need your help. Thanks in advance.

**Comment by llfocasan-arch** [comment]
Same here! I am hoping to find a solution here.
