### ISSUE TITLE
Jdbc-Odbc Bridge

### ISSUE THREAD

**Issue by ViktoriaFerenc** [SmartRoot/SmartRoot#7]
Hi,

I tried to install SmartRoot bit for bit, following the manual. I encountered a problem setting up the SQL Adress, according to my internet search this feature is not embedded in Java 8 - can you advise me how to install the software?

Many thanks
Viktoria Ferenc

**Comment by guillaumelobet** [comment]
Dear Vikoria, the easiest way would be to skip the SQL link and export the data as text files (CSV). SQL link is only needed if you want to export to an SQL database

**Comment by ViktoriaFerenc** [comment]
Hi,
Thanks for your quick answer! Alright perfect, I'll be totally happy with a csv file !
