### ISSUE TITLE
SmartRoot not exporting

### ISSUE THREAD

**Issue by 655321SMITH** [SmartRoot/SmartRoot#8]
Hey guys. Im super new to using smartroot so I am sorry if this is an obvious fix. I keep trying to export my root tracings to tiff files. However I hit the export button and the folder I have set up remains empty. I have checked to make sure my file directory is correct. Effectively the entire data transfer tab is not working. Any ideas?

**Comment by guillaumelobet** [comment]
Hey, one thing you can check it wether the folder path is correct. Sometime, SmartRoot will duplicate the last part of the path, pointing to a non-existing folder. This might be one reason why it is not working. 

One other way to visualize the tracing is to use the R package [archiDART](https://archidart.github.io/). It can also be used to analyse the data you traced.
