### ISSUE TITLE
Cannot modify roots on large networks

### ISSUE THREAD

**Issue by hrrrzw** [SmartRoot/SmartRoot#9]
Hello.
I'm using SmartRoot for a project looking at the growth of roots over time. For some of my boxes with over 100 roots, when I import the seed datafile from the previous image, I cannot modify the roots to measure how they've grown. I can't change the position of any nodes, I can't change the root length and I can't even delete them. Is this a known issue? If so, is there a fix? I can make new roots fine on these images, but I can't edit existing roots.
There is no problem with the images containing less than 100 roots.
Thanks.

**Comment by guillaumelobet** [comment]
Hi, this is very strange and I have nevcer heard of that issue. 
Maybe you can send an example of an RSML file and image that is not working, so I can try it out on my side?

**Comment by hrrrzw** [comment]
Hi. I sent a message with some files to the email address on your website

**Comment by hrrrzw** [comment]
Thanks, that worked perfectly!
